### ISSUE TITLE
ElasticSearch needs to be populated with data

### ISSUE THREAD

**Issue by PavlovGrigor** [DITAS-Project/data-analytics#2]
It has to be done by 29th of April

**Comment by tawalaya** [comment]
For Data generated by the VDC have a look at https://github.com/DITAS-Project/TUBMonitoringDataGenerator it can generate the data recorded by the VDC side monitoring components and store it in ES.

**Comment by bogdan-ds** [comment]
@tawalaya there is an error when installing the requirements for the TUBMonitoringDataGenerator:

`# github.com/DITAS-Project/VDC-Logging-Agent/agent
go/src/github.com/DITAS-Project/VDC-Logging-Agent/agent/agent.go:288:35: agent.elastic.PutMapping().Index(agent.getElasticIndex()).Type undefined (type *elastic.IndicesPutMappingService has no field or method Type)
`

Could you look into this, as we can't run the generator otherwise. I've tried with two different golang version 1.11 and 1.10.

**Comment by tawalaya** [comment]
To make it easier to debug could you please document the steps to did?

- order of commands you performed to build and run
- version of elasticserach used
- parameters given to the tool

**Comment by bogdan-ds** [comment]
Hi @tawalaya,

Here's what I have:
```
bogdan@master:~$ go version
go version go1.10.8 linux/amd64
bogdan@master:~$ go get -v github.com/DITAS-Project/TUBMonitoringDataGenerator
github.com/DITAS-Project/VDC-Logging-Agent/agent
# github.com/DITAS-Project/VDC-Logging-Agent/agent
go/src/github.com/DITAS-Project/VDC-Logging-Agent/agent/agent.go:288:35: agent.elastic.PutMapping().Index(agent.getElasticIndex()).Type undefined (type *elastic.IndicesPutMappingService has no field or method Type)
```

When I try to install the logging agent separately:
```
bogdan@master:~$ cd VDC-Logging-Agent/
bogdan@master:~/VDC-Logging-Agent$ go build
# github.com/DITAS-Project/VDC-Logging-Agent/agent
../go/src/github.com/DITAS-Project/VDC-Logging-Agent/agent/agent.go:288:35: agent.elastic.PutMapping().Index(agent.getElasticIndex()).Type undefined (type *elastic.IndicesPutMappingService has no field or method Type)
```

Thanks

**Comment by tawalaya** [comment]
Hi @all, I released an update to the generator today that fixes an issue related to the data generation. I also tried multiple ways (brand new VM, docker go container and my dev machine) to build the generator an all worked. So the issue you mention is either resolved or I can't reproduce it.

In either case a save way to build the generator is to use a docker container to do it. I recommend the following steps:

- git clone the repo somewhere and go into the folder
- `docker run -it --rm -v $(pwd):/opt/build golang bash`
- `cd /opt/build`
- `CGO_ENABLED=0 GOOS=linux go build -a --installsuffix cgo -o generator`
- `exit`

after that you should find a generator binary inside the folder.

Please let me know if that works for you.

**Comment by bogdan-ds** [comment]
Hi @tawalaya, thanks for checking this. I followed the steps above and it didn't work for me. Sorry, I'm not very familiar with docker, so I'm not sure what's wrong exactly, here's the output (note, I'm using sudo, as otherwise there's a permission error when trying to connect to the docker daemon socket):

```
bogdan@master:~/TUBMonitoringDataGenerator$ sudo docker run --rm -v $(pwd):/opt/build golang bash
bogdan@master:~/TUBMonitoringDataGenerator$ cd /opt/build
-bash: cd: /opt/build: No such file or directory
```

**Comment by tawalaya** [comment]
Looks like the docker container did not start the cd and following commands should run inside the docker. Try adding an -it in front of the run command.

**Comment by bogdan-ds** [comment]
Hi @tawalaya, thanks. It seems to be working now, I'm generating events with the gen=1 option, gen=0 did not work for me, but that's fine.
